---
- hosts: workers
  become: yes

  tasks:

    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Start Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Deploy Netflix application
      git:
        repo: "https://github.com/CleverProgrammers/pwj-netflix-clone.git"
        dest: "/var/www/html"
...
